name: Nightly Release

on:
  schedule:
    - cron: '15 9 */2 * *'  # Runs every 2 days at 09:15 UTC (04:15 EST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new --tag ghcr.io/${{ github.repository_owner }}/launchiine:nightly .

    - name: Run custom command
      run: |
        docker run --rm -v $PWD:/project ghcr.io/${{ github.repository_owner }}/launchiine:nightly bash -c 'for file in $(find data -type f); do /opt/devkitpro/tools/bin/bin2s -a 32 "$file" -H "build/$(basename "$file" | tr . _).h"; done'

    - name: Extract build artifacts
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/${{ github.repository_owner }}/launchiine:nightly \
          cp /project/men.rpx /workspace/men.rpx && \
          cp /project/men.elf /workspace/men.elf

    - name: Create release
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: men.rpx, men.elf
