name: Nightly Release

on:
  schedule:
    - cron: '15 7 * * *'  # Runs every day at 07:15 UTC (02:15 EST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for the repository

    - name: Check for changes
      id: changes
      uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process');
          const lastNightlyCommit = execSync('git log -1 --before="24 hours ago" --format="%H"').toString().trim();
          const recentChanges = execSync(`git diff --name-only HEAD ${lastNightlyCommit}`).toString().trim();
          if (!recentChanges) {
            fs.writeFileSync(process.env.GITHUB_OUTPUT, 'changes=false');
          } else {
            fs.writeFileSync(process.env.GITHUB_OUTPUT, 'changes=true');
          }

    - name: Continue only if there are changes
      if: steps.changes.outputs.changes == 'true'
      run: echo "Changes detected, continuing with the build and release."

    - name: Set up Docker Buildx
      if: steps.changes.outputs.changes == 'true'
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      if: steps.changes.outputs.changes == 'true'
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      if: steps.changes.outputs.changes == 'true'
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build Docker image
      if: steps.changes.outputs.changes == 'true'
      run: |
        docker buildx create --use
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new --tag ghcr.io/${{ github.repository_owner }}/launchiine:nightly .

    - name: Run custom command
      if: steps.changes.outputs.changes == 'true'
      run: |
        docker run --rm -v $PWD:/project ghcr.io/${{ github.repository_owner }}/launchiine:nightly bash -c 'for file in $(find data -type f); do /opt/devkitpro/tools/bin/bin2s -a 32 "$file" -H "build/$(basename "$file" | tr . _).h"; done'

    - name: Extract build artifacts
      if: steps.changes.outputs.changes == 'true'
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/${{ github.repository_owner }}/launchiine:nightly \
          cp /project/men.rpx /workspace/men.rpx && \
          cp /project/men.elf /workspace/men.elf

    - name: Create release
      if: steps.changes.outputs.changes == 'true'
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: men.rpx, men.elf

    - name: No changes message
      if: steps.changes.outputs.changes == 'false'
      run: echo "No changes detected since the last nightly release."
